---
- name: Install python3-ldap
  apt:
    pkg: python3-ldap

- name: Create LDAP data path
  file:
    path: "{{ ldap__data_path }}"
    state: directory
    mode: 0775

- name: Copy ldap build files
  copy:
    src: "build"
    dest: "{{ ldap__data_path }}"
    mode: 0775

- name: Build ldap image 
  community.docker.docker_image:
    name: "devops/ldap"
    build:
      path: "{{ ldap__data_path }}/build"
    source: build
    force_source: true

- name: Create open LDAP container
  docker_container:
    name: "{{ ldap__host }}"
    image: "devops/ldap"
    state: started
    restart: no
    restart_policy : always
    comparisons:
      published_ports: strict
    ports: "{{ ldap__port_bindings }}"
    volumes:
     - "{{ ldap__data_path }}/data:/openldap/data"
     - "{{ ldap__data_path }}/slapd.d:/openldap/slapd.d"
    env:
      LDAP_ORGANIZATION: "{{ ldap__organization }}"
      LDAP_DOMAIN: "{{ ldap__domain }}"
      LDAP_BASE_DN: "{{ ldap__base_dn }}"
      LDAP_ADMIN_USERNAME: "{{ ldap__admin_username }}"
      LDAP_ADMIN_PASSWORD: "{{ ldap__admin_password }}"
      LDAP_BIND_USERNAME: "{{ ldap__bind_username }}"
      LDAP_BIND_PASSWORD: "{{ ldap__bind_password }}"
      LDAP_DEFAULT_USERNAME: "{{ ldap__default_username }}"
      LDAP_DEFAULT_PASSWORD: "{{ ldap__default_password }}"
    network_mode: bridge
    networks:
      - name: "{{ ldap__network }}"
